AWSTemplateFormatVersion: 2010-09-09
Description: Academy Demo CloudFormation

Resources:
  piianBucket:
    Type: "AWS::S3::Bucket"

MyQueue:
  Type: AWS::SQS::Queue
  Properties:
    VisibilityTimeout: 30
